name: nlp-hw1
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch>=2.0.0
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - tqdm
  - psutil
  - pip
  - pip:
    - torchprofile
    - fvcore