name: nlp-hw1
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - tqdm
  - psutil
  - scipy
  - scikit-learn
  - faiss-cpu
  - pip
  - pip:
    - torchprofile
    - fvcore
    - transformers
    - peft
    - datasets
    - openai